/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/data-display/': RouteRecordInfo<'/home/data-display/', '/home/data-display', Record<never, never>, Record<never, never>>,
    '/home/data-display/building-display/': RouteRecordInfo<'/home/data-display/building-display/', '/home/data-display/building-display', Record<never, never>, Record<never, never>>,
    '/home/data-display/data-comparison/': RouteRecordInfo<'/home/data-display/data-comparison/', '/home/data-display/data-comparison', Record<never, never>, Record<never, never>>,
    '/home/data-display/data-comparison/LeftPanel': RouteRecordInfo<'/home/data-display/data-comparison/LeftPanel', '/home/data-display/data-comparison/LeftPanel', Record<never, never>, Record<never, never>>,
    '/home/data-display/data-comparison/RightPanel': RouteRecordInfo<'/home/data-display/data-comparison/RightPanel', '/home/data-display/data-comparison/RightPanel', Record<never, never>, Record<never, never>>,
    '/home/data-display/filter': RouteRecordInfo<'/home/data-display/filter', '/home/data-display/filter', Record<never, never>, Record<never, never>>,
    '/home/data-display/summary-display/': RouteRecordInfo<'/home/data-display/summary-display/', '/home/data-display/summary-display', Record<never, never>, Record<never, never>>,
    '/home/data-display/summary-display/LeftPanel': RouteRecordInfo<'/home/data-display/summary-display/LeftPanel', '/home/data-display/summary-display/LeftPanel', Record<never, never>, Record<never, never>>,
    '/home/data-display/summary-display/MapTools': RouteRecordInfo<'/home/data-display/summary-display/MapTools', '/home/data-display/summary-display/MapTools', Record<never, never>, Record<never, never>>,
    '/home/data-display/summary-display/MiddleMap': RouteRecordInfo<'/home/data-display/summary-display/MiddleMap', '/home/data-display/summary-display/MiddleMap', Record<never, never>, Record<never, never>>,
    '/home/data-display/summary-display/RightPanel': RouteRecordInfo<'/home/data-display/summary-display/RightPanel', '/home/data-display/summary-display/RightPanel', Record<never, never>, Record<never, never>>,
    '/home/data-display/unit-heatmap/': RouteRecordInfo<'/home/data-display/unit-heatmap/', '/home/data-display/unit-heatmap', Record<never, never>, Record<never, never>>,
    '/home/data-display/unit-heatmap/LeftPanel': RouteRecordInfo<'/home/data-display/unit-heatmap/LeftPanel', '/home/data-display/unit-heatmap/LeftPanel', Record<never, never>, Record<never, never>>,
    '/home/data-display/unit-heatmap/RightMap': RouteRecordInfo<'/home/data-display/unit-heatmap/RightMap', '/home/data-display/unit-heatmap/RightMap', Record<never, never>, Record<never, never>>,
    '/home/data-processing/': RouteRecordInfo<'/home/data-processing/', '/home/data-processing', Record<never, never>, Record<never, never>>,
    '/home/data-processing/cross-summary/': RouteRecordInfo<'/home/data-processing/cross-summary/', '/home/data-processing/cross-summary', Record<never, never>, Record<never, never>>,
    '/home/data-processing/cross-summary/head-form/Index': RouteRecordInfo<'/home/data-processing/cross-summary/head-form/Index', '/home/data-processing/cross-summary/head-form/Index', Record<never, never>, Record<never, never>>,
    '/home/data-processing/cross-summary/yanshengzhibiao/': RouteRecordInfo<'/home/data-processing/cross-summary/yanshengzhibiao/', '/home/data-processing/cross-summary/yanshengzhibiao', Record<never, never>, Record<never, never>>,
    '/home/data-processing/data-query/': RouteRecordInfo<'/home/data-processing/data-query/', '/home/data-processing/data-query', Record<never, never>, Record<never, never>>,
    '/home/data-processing/quick-summary/': RouteRecordInfo<'/home/data-processing/quick-summary/', '/home/data-processing/quick-summary', Record<never, never>, Record<never, never>>,
    '/home/data-processing/quick-summary/head-form/Index': RouteRecordInfo<'/home/data-processing/quick-summary/head-form/Index', '/home/data-processing/quick-summary/head-form/Index', Record<never, never>, Record<never, never>>,
    '/home/data-processing/quick-summary/yanshengzhibiao/': RouteRecordInfo<'/home/data-processing/quick-summary/yanshengzhibiao/', '/home/data-processing/quick-summary/yanshengzhibiao', Record<never, never>, Record<never, never>>,
    '/home/data-processing/template-summary/': RouteRecordInfo<'/home/data-processing/template-summary/', '/home/data-processing/template-summary', Record<never, never>, Record<never, never>>,
    '/home/data-processing/template-summary/head-form/Index': RouteRecordInfo<'/home/data-processing/template-summary/head-form/Index', '/home/data-processing/template-summary/head-form/Index', Record<never, never>, Record<never, never>>,
    '/home/Thematic-Display/': RouteRecordInfo<'/home/Thematic-Display/', '/home/Thematic-Display', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
